export const blockColors = [
  ["#ee2223", "#12a79d", "#f89f1c"], //bloki 3x3 poziomy 1-3
  ["#8bc63e", "#e64d9c", "#939ea7"], //bloki 3x3 poziomy 4-6
  ["#fff101", "#504077", "#00aeef"], //bloki 3x3 poziomy 7-9
];

export const sections = [
  {
    name: "Kolorowe piksele",
    backgroundColors: false,
    items: [
      { color: "#090102", img: null, isPixel: true },
      { color: "#939ea6", img: null, isPixel: true },
      { color: "#f7ec12", img: null, isPixel: true },
      { color: "#ebe5c4", img: null, isPixel: true },
      { color: "#faa41a", img: null, isPixel: true },
      { color: "#ec008c", img: null, isPixel: true },
      { color: "#ed1e24", img: null, isPixel: true },
      { color: "#613d18", img: null, isPixel: true },
      { color: "#498ccb", img: null, isPixel: true },
      { color: "#292874", img: null, isPixel: true },
      { color: "#8066ad", img: null, isPixel: true },
      { color: "#288b43", img: null, isPixel: true },
    ],
  },
  {
    name: "Krążki kodowanie dla najmłodszych",
    backgroundColors: false,
    items: [
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/1.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/2.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/3.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/4.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/5.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/6.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/7.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/8.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/9.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/10.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/11.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/12.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/13.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/14.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/15.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/16.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/17.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/18.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/19.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/20.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/21.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/22.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/23.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/24.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/25.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/26.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/27.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/28.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/29.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/30.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/31.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/32.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/33.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/34.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/35.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/36.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/37.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/38.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/39.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/40.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/41.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/42.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/43.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/44.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/45.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/46.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/47.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/48.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/49.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/50.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/51.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/52.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/53.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/54.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/55.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/56.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/57.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/58.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/59.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/60.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/61.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/62.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/63.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/64.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/65.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/66.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/67.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/68.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/69.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/70.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/71.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/72.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/73.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/74.png" },
      { color: "#ffffff", img: "./assets/kodowanie_dla_najmlodszych/75.png" },
    ],
  },
  {
    name: "Krążki obrazkowe sudoku",
    backgroundColors: [
      "#ee2223",
      "#12a79d",
      "#f89f1c",
      "#8bc63e",
      "#e64d9c",
      "#939ea7",
      "#fff101",
      "#504077",
      "#00aeef",
      "#ffffff",
    ],
    items: [
      { color: null, img: "./assets/kolorowe_sudoku/1.png" },
      { color: null, img: "./assets/kolorowe_sudoku/2.png" },
      { color: null, img: "./assets/kolorowe_sudoku/3.png" },
      { color: null, img: "./assets/kolorowe_sudoku/4.png" },
      { color: null, img: "./assets/kolorowe_sudoku/5.png" },
      { color: null, img: "./assets/kolorowe_sudoku/6.png" },
      { color: null, img: "./assets/kolorowe_sudoku/7.png" },
      { color: null, img: "./assets/kolorowe_sudoku/8.png" },
      { color: null, img: "./assets/kolorowe_sudoku/9.png" },
      { color: "#ffffff", img: "./assets/kolorowe_sudoku/10.png" },
      { color: "#ffffff", img: "./assets/kolorowe_sudoku/11.png" },
      { color: "#ffffff", img: "./assets/kolorowe_sudoku/12.png" },
      { color: "#ffffff", img: "./assets/kolorowe_sudoku/13.png" },
      { color: "#ffffff", img: "./assets/kolorowe_sudoku/14.png" },
      { color: "#ffffff", img: "./assets/kolorowe_sudoku/15.png" },
      { color: "#ffffff", img: "./assets/kolorowe_sudoku/16.png" },
      { color: "#ffffff", img: "./assets/kolorowe_sudoku/17.png" },
      { color: "#ffffff", img: "./assets/kolorowe_sudoku/18.png" },
      { color: "#ffffff", img: "./assets/kolorowe_sudoku/19.png" },
      { color: "#ffffff", img: "./assets/kolorowe_sudoku/20.png" },
      { color: "#ffffff", img: "./assets/kolorowe_sudoku/21.png" },
      { color: "#ffffff", img: "./assets/kolorowe_sudoku/22.png" },
      { color: "#ffffff", img: "./assets/kolorowe_sudoku/23.png" },
      { color: "#ffffff", img: "./assets/kolorowe_sudoku/24.png" },
      { color: "#ffffff", img: "./assets/kolorowe_sudoku/25.png" },
      { color: "#ffffff", img: "./assets/kolorowe_sudoku/26.png" },
      { color: "#ffffff", img: "./assets/kolorowe_sudoku/27.png" },
      { color: "#ffffff", img: "./assets/kolorowe_sudoku/28.png" },
      { color: "#ffffff", img: "./assets/kolorowe_sudoku/29.png" },
      { color: "#ffffff", img: "./assets/kolorowe_sudoku/30.png" },
      { color: "#ffffff", img: "./assets/kolorowe_sudoku/31.png" },
    ],
  },
  {
    name: "Krążki symbole do kodowania",
    backgroundColors: false,
    items: [
      {
        color: "#4466b0",
        img: "./assets/symbole_do_kodowania/img1.png",
        isCodingDisc: true,
      },
      {
        color: "#4466b0",
        img: "./assets/symbole_do_kodowania/img2.png",
        isCodingDisc: true,
      },
      {
        color: "#4466b0",
        img: "./assets/symbole_do_kodowania/img3.png",
        isCodingDisc: true,
      },
      {
        color: "#4466b0",
        img: "./assets/symbole_do_kodowania/img4.png",
        isCodingDisc: true,
      },
      {
        color: "#4466b0",
        img: "./assets/symbole_do_kodowania/img5.png",
        isCodingDisc: true,
      },
      {
        color: "#4466b0",
        img: "./assets/symbole_do_kodowania/img6.png",
        isCodingDisc: true,
      },
      {
        color: "#4466b0",
        img: "./assets/symbole_do_kodowania/img7.png",
        isCodingDisc: true,
      },
      {
        color: "#4466b0",
        img: "./assets/symbole_do_kodowania/img8.png",
        isCodingDisc: true,
      },
      {
        color: "#4466b0",
        img: "./assets/symbole_do_kodowania/img9.png",
        isCodingDisc: true,
      },
      {
        color: "#4466b0",
        img: "./assets/symbole_do_kodowania/img10.png",
        isCodingDisc: true,
      },
      {
        color: "#4466b0",
        img: "./assets/symbole_do_kodowania/img11.png",
        isCodingDisc: true,
      },
      {
        color: "#4466b0",
        img: "./assets/symbole_do_kodowania/img12.png",
        isCodingDisc: true,
      },
      {
        color: "#4466b0",
        img: "./assets/symbole_do_kodowania/img13.png",
        isCodingDisc: true,
      },
    ],
  },
  {
    name: "Krążki kolorowa matematyka",
    backgroundColors: [
      "#ee2223",
      "#12a79d",
      "#f89f1c",
      "#8bc63e",
      "#e64d9c",
      "#939ea7",
      "#fff101",
      "#504077",
      "#00aeef",
      "#ffffff",
    ],
    items: [
      { color: null, img: "./assets/kolorowa_matematyka/1.png" },
      { color: null, img: "./assets/kolorowa_matematyka/2.png" },
      { color: null, img: "./assets/kolorowa_matematyka/3.png" },
      { color: null, img: "./assets/kolorowa_matematyka/4.png" },
      { color: null, img: "./assets/kolorowa_matematyka/5.png" },
      { color: null, img: "./assets/kolorowa_matematyka/6.png" },
      { color: null, img: "./assets/kolorowa_matematyka/7.png" },
      { color: null, img: "./assets/kolorowa_matematyka/8.png" },
      { color: null, img: "./assets/kolorowa_matematyka/9.png" },
      { color: null, img: "./assets/kolorowa_matematyka/10.png" },
      { color: "#ffffff", img: "./assets/kolorowa_matematyka/11.png" },
      { color: "#ffffff", img: "./assets/kolorowa_matematyka/12.png" },
      { color: "#ffffff", img: "./assets/kolorowa_matematyka/13.png" },
      { color: "#ffffff", img: "./assets/kolorowa_matematyka/14.png" },
      { color: "#ffffff", img: "./assets/kolorowa_matematyka/15.png" },
      { color: "#ffffff", img: "./assets/kolorowa_matematyka/16.png" },
      { color: "#ffffff", img: "./assets/kolorowa_matematyka/17.png" },
      { color: "#ffffff", img: "./assets/kolorowa_matematyka/18.png" },
      { color: "#ffffff", img: "./assets/kolorowa_matematyka/19.png" },
      { color: "#ffffff", img: "./assets/kolorowa_matematyka/20.png" },
      { color: "#ffffff", img: "./assets/kolorowa_matematyka/21.png" },
      { color: "#ffffff", img: "./assets/kolorowa_matematyka/22.png" },
    ],
  },
  {
    name: "Krążki materiał obrazkowy",
    backgroundColors: false,
    items: [
      { color: "#ffffff", img: "./assets/material_obrazkowy/1.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/2.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/3.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/4.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/5.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/6.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/7.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/8.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/9.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/10.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/11.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/12.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/13.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/14.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/15.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/16.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/17.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/18.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/19.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/20.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/21.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/22.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/23.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/24.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/25.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/26.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/27.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/28.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/29.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/30.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/31.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/32.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/33.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/34.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/35.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/36.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/37.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/38.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/39.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/40.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/41.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/42.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/43.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/44.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/45.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/46.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/47.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/48.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/49.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/50.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/51.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/52.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/53.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/54.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/55.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/56.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/57.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/58.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/59.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/60.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/61.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/62.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/63.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/64.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/65.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/66.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/67.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/68.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/69.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/70.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/71.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/72.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/73.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/74.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/75.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/76.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/77.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/78.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/79.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/80.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/81.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/82.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/83.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/84.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/85.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/86.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/87.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/88.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/89.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/90.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/91.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/92.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/93.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/94.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/95.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/96.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/97.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/98.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/99.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/100.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/101.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/102.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/103.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/104.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/105.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/106.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/107.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/108.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/109.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/110.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/111.png" },
      { color: "#ffffff", img: "./assets/material_obrazkowy/112.png" },
    ],
  },
];
