export const boardGameState = {
  frontSizeRows: 9,
  backSizeRows: 10,
  cellSize: 80,
  isFront: true,
  dragging: null,
  prevPiece: null,
  loadedImages: {},
  piecesFront: [],
  piecesGrid: [],
  lockedImg: null,
  codeRows: 3,
  codeMargin: 0,
  isPainting: false,
  paintColor: null,
};
